/**
 * Referência: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status
 */

export enum HttpStatusEnum {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  MOVED_TEMPORARILY = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  REQUEST_ENTITY_TOO_LARGE = 413,
  REQUEST_URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  IM_A_TEAPOT = 418,
  INSUFFICIENT_SPACE_ON_RESOURCE = 419,
  METHOD_FAILURE = 420,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  INSUFFICIENT_STORAGE = 507,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
}

export const getStatusText = (code: number | HttpStatusEnum): string => {
  if (messages.hasOwnProperty(code)) {
    return messages[code];
  }

  throw new Error('Código do status da requisição não encontrado: ' + code);
};

const messages: any = {
  [HttpStatusEnum.CONTINUE]: 'Continuar',
  [HttpStatusEnum.SWITCHING_PROTOCOLS]: 'Mudando protocolos',
  [HttpStatusEnum.PROCESSING]: 'Processamento',
  [HttpStatusEnum.OK]: 'OK',
  [HttpStatusEnum.CREATED]: 'Criado',
  [HttpStatusEnum.ACCEPTED]: 'Aceito',
  [HttpStatusEnum.NON_AUTHORITATIVE_INFORMATION]: 'Não autorizado',
  [HttpStatusEnum.NO_CONTENT]: 'Nenhum conteúdo',
  [HttpStatusEnum.RESET_CONTENT]: 'Conteúdo resetado',
  [HttpStatusEnum.PARTIAL_CONTENT]: 'Conteúdo parcial',
  [HttpStatusEnum.MULTI_STATUS]: 'Status Multi',
  [HttpStatusEnum.MULTIPLE_CHOICES]: 'Múltipla escolha',
  [HttpStatusEnum.MOVED_PERMANENTLY]: 'Movido permanentemente',
  [HttpStatusEnum.MOVED_TEMPORARILY]: 'Movido temporariamente',
  [HttpStatusEnum.SEE_OTHER]: 'Veja outro',
  [HttpStatusEnum.NOT_MODIFIED]: 'Não modificado',
  [HttpStatusEnum.USE_PROXY]: 'Use o proxy',
  [HttpStatusEnum.TEMPORARY_REDIRECT]: 'Redirecionamento temporário',
  [HttpStatusEnum.PERMANENT_REDIRECT]: 'Redirecionamento permanente',
  [HttpStatusEnum.BAD_REQUEST]: 'Requisição inválida',
  [HttpStatusEnum.UNAUTHORIZED]: 'Não autorizado',
  [HttpStatusEnum.PAYMENT_REQUIRED]: 'Pagamento requerido',
  [HttpStatusEnum.FORBIDDEN]: 'Acesso proibido',
  [HttpStatusEnum.NOT_FOUND]: 'Não encontrado',
  [HttpStatusEnum.METHOD_NOT_ALLOWED]: 'Método não permitido',
  [HttpStatusEnum.NOT_ACCEPTABLE]: 'Não aceitável',
  [HttpStatusEnum.PROXY_AUTHENTICATION_REQUIRED]: 'Autenticação de proxy necessária',
  [HttpStatusEnum.REQUEST_TIMEOUT]: 'Tempo de requisição esgotou',
  [HttpStatusEnum.CONFLICT]: 'Conflito',
  [HttpStatusEnum.GONE]: 'Recurso não está mais disponível',
  [HttpStatusEnum.LENGTH_REQUIRED]: 'Tamanho requerido',
  [HttpStatusEnum.PRECONDITION_FAILED]: 'Pré-condição falhou',
  [HttpStatusEnum.REQUEST_ENTITY_TOO_LARGE]: 'Entidade requisitada muito grande',
  [HttpStatusEnum.REQUEST_URI_TOO_LONG]: 'URI requisitada muito grande',
  [HttpStatusEnum.UNSUPPORTED_MEDIA_TYPE]: 'Tipo de mídia não suportado',
  [HttpStatusEnum.REQUESTED_RANGE_NOT_SATISFIABLE]: 'Range requisitado não satisfatório',
  [HttpStatusEnum.EXPECTATION_FAILED]: 'Falha na expectativa',
  [HttpStatusEnum.IM_A_TEAPOT]: 'Eu sou um bule de chá',
  [HttpStatusEnum.INSUFFICIENT_SPACE_ON_RESOURCE]: 'Recurso com espaço insuficiente',
  [HttpStatusEnum.METHOD_FAILURE]: 'Método falhou',
  [HttpStatusEnum.UNPROCESSABLE_ENTITY]: 'Entidade não processável',
  [HttpStatusEnum.LOCKED]: 'Fechado',
  [HttpStatusEnum.FAILED_DEPENDENCY]: 'Falha de dependência',
  [HttpStatusEnum.PRECONDITION_REQUIRED]: 'Pré-condição requerida',
  [HttpStatusEnum.TOO_MANY_REQUESTS]: 'Muitas requisições',
  [HttpStatusEnum.REQUEST_HEADER_FIELDS_TOO_LARGE]: 'Campos do cabeçalho da requisição muito grande',
  [HttpStatusEnum.INTERNAL_SERVER_ERROR]: 'Erro interno do servidor',
  [HttpStatusEnum.NOT_IMPLEMENTED]: 'Não implementado',
  [HttpStatusEnum.BAD_GATEWAY]: 'Gateway ruim',
  [HttpStatusEnum.SERVICE_UNAVAILABLE]: 'Serviço indisponível',
  [HttpStatusEnum.GATEWAY_TIMEOUT]: 'Tempo do gateway esgotou',
  [HttpStatusEnum.HTTP_VERSION_NOT_SUPPORTED]: 'Versão HTTP não suportada',
  [HttpStatusEnum.INSUFFICIENT_STORAGE]: 'Espaço insuficiente',
  [HttpStatusEnum.NETWORK_AUTHENTICATION_REQUIRED]: 'Autenticação de rede requerida',
};
